### PR TITLE
Changes for Embarcadero C++ clang-based compilers, targeting Boost 1.74

### PR DESCRIPTION
**Pull request by eldiener**

### CODE REVIEW

**Comment by eldiener** [comment]
The failure on Travis has nothing to do with these changes. I do not understand the failure on AppVeyor as it refers to something in boost/core which does not correspond to anything I have locally.

**Comment by eldiener** [comment]
How do I retrigger the travis and/or appveyor tests without making a further change to the PR ? The header file from boost.core that was causing the appveyor failure has been updated since the test and the travis failure looks like it has something to do with a travis failure.

**Comment by jzmaddock** [comment]
For appveyor there's a "Re run incomplete" button which restarts failed runs.  Maybe only the repro owner sees it though?  I've restarted though...

**Comment by eldiener** [comment]
Where is this "Re run incomplete" button supposed to be ? I do not see it on the Github page next to the CI test for the particular "check", so maybe you are right that only the repro owner is able to do it. It does seem odd that the person issuing the PR can not rerun some CI test. Thanks for rerunning the tests.

**Comment by jzmaddock** [comment]
screen2
screen1

**Comment by eldiener** [comment]
> 
> 
> screen2
> screen1

Got it ! Thanks !

**Comment by eldiener** [comment]
Can this please be merged ?

**Comment by eldiener** [comment]
Is there any reason that this can not be merged ? There are no conflicts and all tests pass.

**Comment by eldiener** [comment]
Can this please be merged ?

**Pull request merged**
