### PR TITLE
fix #227

### LINKED ISSUE #227: Out of bounds access with specially crafted regular expression
Running the following program under debug gives an error `xstring(1902) : Assertion failed: cannot dereference string iterator because it is out of range (e.g. an end iterator)`:

```cpp
#include <boost/regex.hpp>
#include <string>

int main() {
   boost::regex rx("(*ACCEPT)*+\\1((*ACCEPT)*+\\K)");
   std::string str = "Z";
   boost::smatch what;
   boost::regex_search(str, what, rx, boost::match_default|boost::match_partial);
}
```

Tested on Windows, compiler: Visual Studio 2019.

The above regular expression was found via fuzzing.

### PR DESCRIPTION
**Pull request by cmazakas**
This PR contains a draft of a fix for issue #227. I call it a draft because while the condition seems to fix the issue and all the tests pass, I have no idea why it works or why it's correct.

@jzmaddock hopefully this "fix" will help give you some insight as to how I should clean this up.

Edit:

Before we merge, let me squash all the commits in this branch.

### CODE REVIEW

**Comment by jzmaddock** [comment]
No.  I don't know why it works either... except that it avoids the issue rather than fixes it because the call to match_endmark at line 1190 for sub-expression $1 is not reached any more with the change in place.  This is why I hate fuzzer derived test cases (and some of the fancier Perl extensions) as they generate state machines which no mere mortal can understand!  Actually, this one should be simple enough to figure out eventually... but whether it's worth the time is another matter.

For preference I would remove the `if (idx == -5)` check and call match_startmark unconditionally here: in general match_startmark and match_endmark calls should always be balanced: if they're not then something has gone wrong!  So that piece of code looks suspicious to me anyway (the tests all pass with that change too).

BTW the Jamfile for test_grep had got badly broken recently with the Boost.Build changes, I've just pushed a fix for that.

**Comment by cmazakas** [comment]
> For preference I would remove the `if (idx == -5)` check and call match_startmark unconditionally here: in general match_startmark and match_endmark calls should always be balanced: if they're not then something has gone wrong! So that piece of code looks suspicious to me anyway (the tests all pass with that change too).

I tried this initially but it made quite a few tests fail. Using the conditional check, everything passes.

**Comment by jzmaddock** [comment]
That's weird, see: https://github.com/boostorg/regex/pull/230

**Comment by cmazakas** [comment]
Closing in favor of your PR, John

**Pull request closed without merging**
