### PR TITLE
Move forward to C++11 version that can be used standalone.

### PR DESCRIPTION
**Pull request by jzmaddock**

### CODE REVIEW

**Comment by Mike-Devel** [comment]
Please give a heads up, when this is ready to test.

**Comment by jzmaddock** [comment]
@Mike-Devel : This is good to go bar docs, so now would be a good time to test things out.  Standalone mode is activated either by defining BOOST_REGEX_STANDALONE, or by just not having boost in your include path as long as the compiler supports __has_include.

**Comment by Kojoley** [comment]
This broke Spirit as it uses `boost/regex/pending/unicode_iterator.hpp`, what should I use instead?

**Comment by jzmaddock** [comment]
> This broke Spirit as it uses boost/regex/pending/unicode_iterator.hpp, what should I use instead?

Oh :(  I'll add a forwarding header tomorrow.

**Comment by jzmaddock** [comment]
> This broke Spirit as it uses boost/regex/pending/unicode_iterator.hpp, what should I use instead?

Header reinstated.  Thanks for spotting that!

**Comment by Kojoley** [comment]
>Header reinstated. Thanks for spotting that!

Thanks!

**Pull request merged**
